version: "3.8"

services:

  app:
    container_name: lite-backend-api
    env_file:
      - .env
    build:
      dockerfile: src/Dockerfile
      context: .
    image: lite-backend-api
    ports:
      - "${LITE_BACK_PORT}:8000"
    restart: always
    networks:
      - internal


networks:
  internal:

