version: "3.8"

services:

  app:
    container_name: lite-backend-api
#    env_file:
#      - .env
    environment:
      - LS_PORT=${LS_PORT}
      - LS_PUB_KEY=${LS_PUB_KEY}
    build:
      dockerfile: src/Dockerfile
      context: .
    image: lite-backend-api
    ports:
      - "${LITE_BACK_PORT}:8000"
    restart: always
    networks:
      - internal


networks:
  internal:

